### PR TITLE
#38 Added Custom Gradient ScrollBar

### PR DESCRIPTION
**Pull request by aakashraj01**
#38 Solved
Added Gradient ScrollBar shown below
Scrollbar - Made with Clipchamp

### CODE REVIEW

**Comment by lovishprabhakar** [comment]
@aakashraj01 Fetch the upstream on your fork and then we're good to go!

**Comment by aakashraj01** [comment]
Ok @lovishprabhakar doin right now

**Comment by aakashraj01** [comment]
@lovishprabhakar Done fetch and upstream..Can you now able to merge it

**Comment by aakashraj01** [comment]
@lovishprabhakar Are you able to merge it ? or is there any issue happened

**Comment by lovishprabhakar** [comment]
@aakashraj01 why did you close the Pull Request?
There are no issues, are you working on something or shall I merge this one?

**Comment by aakashraj01** [comment]
@lovishprabhakar Merge this one ..actually I thought there is some issue in this pr

**Comment by lovishprabhakar** [comment]
merging. Good work! @aakashraj01

**Comment by aakashraj01** [comment]
@lovishprabhakar Thank You so much for merging my contribution...

**Pull request merged**
