### PR TITLE
changes in contest page

### PR DESCRIPTION
**Pull request by rahul-n18**

### CODE REVIEW

**Comment by rahul-n18** [comment]
added few new images to contest page

**Comment by lovishprabhakar** [comment]
@rahul-n18 can you provide a screenshot of the changes you made?

**Comment by rahul-n18** [comment]
Below are the changed pics

Screenshot (37)

Screenshot (38)

**Comment by lovishprabhakar** [comment]
Good work @rahul-n18!

**Comment by rahul-n18** [comment]
Thank you,
One thing i just needed to ask you, I am very new to this Hacktoberfest, so as now you have merged my request will I get a badge?

**Pull request merged**
