### PR TITLE
added favicon

### PR DESCRIPTION
**Pull request by sanvi0071**

### CODE REVIEW

**Comment by lovishprabhakar** [comment]
@sanvi0071 please provide screenshot of the website showing the favicon.

**Comment by sanvi0071** [comment]
Screenshot (29)

its visible in the address bar top-left side

**Comment by lovishprabhakar** [comment]
> Screenshot (29)
> 
> its visible in the address bar top-left side

ok, so now all you need to do is:
1. Click on the "Sync Fork" Option next to "Contribute" which is used to open pull request.
2. Click on "Fetch Upstream".
Let me know when done.

**Comment by lovishprabhakar** [comment]
Don't forget to star the repository :)

**Comment by lovishprabhakar** [comment]
Good work @sanvi0071!

**Pull request merged**
