### PR TITLE
Making the images clickable

### PR DESCRIPTION
**Pull request by Kaushik-Iyer**
Solves Issue #10

### CODE REVIEW

**Comment by lovishprabhakar** [comment]
branch up to date @Kaushik-Iyer ?

**Comment by Kaushik-Iyer** [comment]
Yeah I made it up to date and changed again.

**Comment by lovishprabhakar** [comment]
Good, thanks for all your efforts! Really great work.

**Comment by lovishprabhakar** [comment]
wait, while merging it still shows not up to date, fetch upstream for one last time and we're good to go

**Comment by Kaushik-Iyer** [comment]
> wait, while merging it still shows not up to date, fetch upstream for one last time and we're good to go @Kaushik-Iyer

I think it is because you merge other pull requests before this one, so mine shows as lagging behind

**Pull request merged**
