### PR TITLE
Making the images clickable again

### PR DESCRIPTION
**Pull request by Kaushik-Iyer**
Solves issue #10 , which was re-opened due to an issue causing the UI to revert

### CODE REVIEW

**Comment by lovishprabhakar** [comment]
@Kaushik-Iyer fetch upstream and then I'll merge the pdf

**Comment by Kaushik-Iyer** [comment]
I don't understand

**Comment by lovishprabhakar** [comment]
1. Click on the "Sync Fork" Option next to "Contribute" which is used to open pull request.
2. Click on "Fetch Upstream".
Let me know when done.

> I don't understand

**Comment by lovishprabhakar** [comment]
Don't forget to star the repository :)

**Comment by Kaushik-Iyer** [comment]
> 

Discard 1 commit to make this branch match the upstream repository. 1 commit will be removed from this branch.
I'll have to remove my changes to do that i guess, and again make all my changes..

**Comment by lovishprabhakar** [comment]
yes, I know it's hectic but without it problems might arise. So please do that

**Comment by lovishprabhakar** [comment]
Tip: Always ensure that your branch is up to date before making changes

**Comment by Kaushik-Iyer** [comment]
okay, hopefully this is the last time lol

**Comment by lovishprabhakar** [comment]
yes just please wait for a couple of minutes, I'll comment here and then you can fetch the upstream

**Pull request closed without merging**
