### PR TITLE
Fixed the card's animation.

### PR DESCRIPTION
**Pull request by hs-07**

### CODE REVIEW

**Comment by lovishprabhakar** [comment]
And a new card has been added so please update your fork and add the animation to that one as well. @hs-07

**Comment by hs-07** [comment]
Here is the clip

https://user-images.githubusercontent.com/87127387/193860292-812cc6f9-499d-468e-8a45-5954d0edcaa4.mp4

**Comment by hs-07** [comment]
@lovishprabhakar 
these changes are applied to all the cards, so dont worry

**Comment by lovishprabhakar** [comment]
Great work @hs-07!

**Pull request merged**
