### PR TITLE
gap between quote and nav added

### PR DESCRIPTION
**Pull request by raunak-dev-edu**
I have added a Gap between quote and nav. Now it's looking better.

### CODE REVIEW

**Comment by lovishprabhakar** [comment]
@raunak-dev-edu please fetch upstream, after that only I can merge

**Comment by raunak-dev-edu** [comment]
> @raunak-dev-edu please fetch upstream, after that only I can merge

try now to merge this PR, I have solved the merged conflict

**Comment by lovishprabhakar** [comment]
> > @raunak-dev-edu please fetch upstream, after that only I can merge
> 
> try now to merge this PR, I have solved the merged conflict

you need to do it again.

**Comment by raunak-dev-edu** [comment]
> > > @raunak-dev-edu please fetch upstream, after that only I can merge
> > 
> > 
> > try now to merge this PR, I have solved the merged conflict
> 
> you need to do it again.

I try to do it again. Check now.

**Pull request merged**
