### PR TITLE
I have Modified the code for Index page where Footer was a blank box (fixes #62 & #64)

### LINKED ISSUE #62: Blank Card needs to be removed/modified
Screenshot (41)

### PR DESCRIPTION
**Pull request by rahul-n18**
This Actually fixes 2 issues #62  and #64 

Screenshot (47)

### CODE REVIEW

**Comment by rahul-n18** [comment]
@lovishprabhakar  Once check and use can close Both the Issue

**Comment by lovishprabhakar** [comment]
@rahul-n18 can you provide a screenshot of the navbar as well?

**Comment by rahul-n18** [comment]
Hello @lovishprabhakar  Could you merge this now please,
I'm Working on something else currently.
By tmw mrg ill Update it.

**Comment by lovishprabhakar** [comment]
alright, good work @rahul-n18!

**Pull request merged**
