### PR TITLE
Making the images clickable

### PR DESCRIPTION
**Pull request by Kaushik-Iyer**
Solves issue #10

### CODE REVIEW

**Comment by lovishprabhakar** [comment]
Good work @Kaushik-Iyer!

**Comment by lovishprabhakar** [comment]
@Kaushik-Iyer could you do the work again? There was an issue so I had to revert the UI back to the initial phase. Please make the images clickable again.

**Comment by Kaushik-Iyer** [comment]
Okay, I'll do it tomorrow

**Comment by Kaushik-Iyer** [comment]
#26 I've done it

**Comment by Kaushik-Iyer** [comment]
@lovishprabhakar can you mark my earlier PRs as invalid except the last one? They're coming up as duplicates on my hacktoberfest profile, I might get disqualified for spam :(

**Comment by lovishprabhakar** [comment]
On it @Kaushik-Iyer, don't worry :)

**Comment by Kaushik-Iyer** [comment]
thanks, all the duplicates have been removed!

**Pull request merged**
