### PR TITLE
added animation

### PR DESCRIPTION
**Pull request by AliReza1083**
I've added some simple animation on cards.
when you refresh the website, the cards are appearing and coming from top to bottom.

### CODE REVIEW

**Comment by lovishprabhakar** [comment]
@AliReza1083 can you provide a video/gif of the animation?

**Comment by AliReza1083** [comment]
Ok

**Comment by AliReza1083** [comment]
Video: 👇
https://drive.google.com/file/d/1vx0pGx02FCKLfqja_N9feYs67bvTFr_B/view?usp=sharing

**Comment by AliReza1083** [comment]
is it okay?

**Comment by lovishprabhakar** [comment]
I don't have access to the video @AliReza1083

**Comment by AliReza1083** [comment]
any social media that I can send it to you? @lovishprabhakar

**Comment by lovishprabhakar** [comment]
Just insert the video here in the comments

**Comment by AliReza1083** [comment]
can we do it?!!
let me try

**Comment by AliReza1083** [comment]
https://user-images.githubusercontent.com/99729607/194005141-b8722009-c5d4-44c7-80cb-631d89e3fd19.mp4

@lovishprabhakar

**Comment by lovishprabhakar** [comment]
Great work @AliReza1083!

**Comment by AliReza1083** [comment]
Thanks @lovishprabhakar

**Pull request merged**
